version: '3.8'

services:
  db:
   container_name: postgres_container
   image: postgres
   ports:
    - 5432:5432
   environment:
    - POSTGRES_USER=john
    - POSTGRES_PASSWORD=123456
    - POSTGRES_DB=test
    - PGDATA=/var/lib/postgresql/data/pgdata
   volumes:
    - ./data/postgres:/var/lib/postgresql/data/pgdata
  
  admin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - db