version: '3.8'

services:
  db:
   container_name: postgres_container
   image: postgres
   ports:
    - 5432:5432
   environment:
    - POSTGRES_USER=john
    - POSTGRES_PASSWORD=123456
    - POSTGRES_DB=test
    - PGDATA=/var/lib/postgresql/data/pgdata
   volumes:
    - ./data/postgres:/var/lib/postgresql/data/pgdata
