version: '3.8'

services:

  panel:
   container_name: python_container
   build:
    context: ./
    dockerfile: Dockerfile
   ports: 
    - "5000:5000"
   volumes:
    - './:/code' 
   environment:
    FLASK_ENV: development
   networks:
    - python

  db:
    container_name: postgres_container
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=test
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    networks:
      - python


  admin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - python


networks:
  python:
    name: python
    driver: bridge